apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::712389989807:user/power-fit-gym-iam
      username: github-actions
      groups:
        - system:masters
