apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shahith/powerfit-gym:latest-backend
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: powerfit_gym
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: shahith
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
