name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: powerfit_gym
      DB_USER: postgres
      DB_PASSWORD: shahith
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: powerfit_gym
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: shahith
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install
      - name: Run tests
        working-directory: ./backend
        run: npm test
      - name: Frontend build
        working-directory: ./frontend
        run: npm install && npm run build

 # sonarqube-analysis:
  #  runs-on: ubuntu-latest
   # needs: build-and-scan
    #steps:
    #- uses: actions/checkout@v6
      #with:
       # # Disabling shallow clones is recommended for improving the relevancy of reporting
     #   fetch-depth: 0
    #- name: SonarQube Scan
     # uses: SonarSource/sonarqube-scan-action@<action version or sha1> # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      #env:
       # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  trivy-check:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy scanner backend
        uses: aquasecurity/trivy-action@v0.36.0
        continue-on-error: true
        with:
           scan-type: 'fs'
           scan-ref: '.'
           severity: 'CRITICAL,HIGH'
           working-dir: './backend'
      - name: Run Trivy scanner frontend
        uses: aquasecurity/trivy-action@v0.36.0
        continue-on-error: true
        with:
           scan-type: 'fs'
           scan-ref: '.'
           severity: 'CRITICAL,HIGH'
           working-dir: './frontend'


           
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker backend image
        run: docker build -t  shahith/powerfit-gym:latest-backend ./backend
      - name: build docker frontend image
        run: docker build -t  shahith/powerfit-gym-frontend:latest-frontend ./frontend
      - name: scan docker backendimage
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          scan-ref: 'shahith/powerfit-gym:latest-backend' 
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
      - name: Push backend image to Docker Hub
        run: docker push shahith/powerfit-gym:latest-backend
      - name: scan docker frontend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          scan-ref: 'shahith/powerfit-gym-frontend:latest-frontend'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
      - name: Push frontend image to Docker Hub
        run: docker push shahith/powerfit-gym-frontend:latest-frontend
 


  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig \
         --region ap-south-1 \
         --name power-gum-cluster
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/db-deployment.yaml
          kubectl apply -f k8s/db-service.yaml
      